wolverine = Comic.create({title: "Wolverine", published: 1976, author:"Benjamin Percy", illustrator:"Victor Bogdanovic", summary: "Wolverine is the prisoner of dracula" })
falcon = Comic.create({title: "Falcon & Winter soldier", published: 2020, author: "Derek Landy", illustrator: "Dustin Weaver", summary: "Raging battle trying to take down Hydra" })
thor = Comic.create({title: "Thor", published: 2019, author: "Tom Defalco", illustrator: "Mike Hawthorne", summary: "Thor reunites with asgard for thunder celebration" })
captain_marvel = Comic.create({title: "Captain Marvel", published: 2020, author: "Kelly Thomston", illustrator: "Corey Smith", summary: "Captain marvel and her crew are suddently ambushed by mandolin" })
black_panther = Comic.create({title: "Black Panther", published: 2019, author: "Jim Zub", illustrator: "Scot Eaton", summary: "Agents of Wakanda come against aliens"})
fantastic_four = Comic.create({title: "Fantastic Four", published: 2002, author: "Nick Bradshaw", illustrator: "Scot Eaton", summary: "Gain super abilities from accident"})
avengers = Comic.create({title: "Avengers", published: 2019, author: "Jonathon Hickman", illustrator: "Dustin Weaver", summary: "Earths mightest heros"})
