wolverine = Comic.create({name: "Wolverine", published:09/10/1976, author:"Benjamin Percy", illustrator:"Victor Bogdanovic", summary: "Wolverine is the prisoner of dracula" })
falcon_&_winter_soldier = Comic.create({name: "Falcon & Winter soldier", published:09/25/2020, author: "Derek Landy", illustrator: "Dustin Weaver", summary: "Raging battle trying to take down Hydra" })
thor = Comic.create({name: "Thor", published: 12/14/2019, author: "Tom Defalco", illustrator: "Mike Hawthorne", summary: "Thor reunites with asgard for thunder celebration" })
captain_marvel = Comic.create({name: "Captain Marvel", published: 07/15/2020, author: "Kelly Thomston", illustrator: "Corey Smith", summary: "Captain marvel and her crew are suddently ambushed by mandolin" })
black_panther = Comic.create({name: "Black Panther", published: 12/09/2019, author: "Jim Zub", illustrator: "Scot Eaton", summary: "Agents of Wakanda come against aliens"})
fantastic_four = Comic.create({name: "Fantastic Four", published: 09/02/2002, author: "Nick Bradshaw", illustrator: "Scot Eaton", summary: "Gain super abilities from accident"})
avengers = Comic.create({name: "Avengers", published: 08/26/2019, author: "Jonathon Hickman", illustrator: "Dustin Weaver", summary: "Earths mightest heros"})
